language: go
sudo: false

env:
  - GO111MODULE=on

go:
  - '1.11.x'
  - '1.12.x'
  - 'tip'

before_install:
  - go get github.com/mattn/goveralls

script:
  - make test
  - goveralls -coverprofile=coverage.out -service=travis-ci
