AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: http proxy

Metadata:
  AWS::ServerlessRepo::Application:
    Name: ssm-sign-proxy
    Description: http proxy with aws lambda
    Author: Shogo Ichinose
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['tests']
    HomePageUrl: https://github.com/shogo82148/ssm-sign-proxy
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/shogo82148/ssm-sign-proxy

Resources:
  Proxy:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ssm-sign-proxy
      Runtime: go1.x
      Timeout: 30
      CodeUri: release/latest/ssm-sign-proxy-function.zip
